Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matminer.datasets import load_dataset
from matminer.featurizers.conversions import StrToComposition

df = load_dataset("matbench_expt_is_metal")
df = df.rename(columns={"composition": "comps"})
result = df['is_metal'].astype(int)
df['is_metal'] = result

# # Convert the formula to a composition object
stc = StrToComposition()
df = stc.featurize_dataframe(df, "comps", pbar=False)

df.groupby(['is_metal']).count()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mUserWarning[0m                               Traceback (most recent call last)
Cell [0;32mIn [10], line 4[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatminer[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatasets[39;00m [38;5;28;01mimport[39;00m load_dataset
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatminer[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfeaturizers[39;00m[38;5;21;01m.[39;00m[38;5;21;01mconversions[39;00m [38;5;28;01mimport[39;00m StrToComposition
[0;32m----> 4[0m df [38;5;241m=[39m load_dataset([38;5;124m"[39m[38;5;124mmatbench_expt_is_metal[39m[38;5;124m"[39m)
[1;32m      5[0m df [38;5;241m=[39m df[38;5;241m.[39mrename(columns[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mcomposition[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mcomps[39m[38;5;124m"[39m})
[1;32m      6[0m result [38;5;241m=[39m df[[38;5;124m'[39m[38;5;124mis_metal[39m[38;5;124m'[39m][38;5;241m.[39mastype([38;5;28mint[39m)

File [0;32m/opt/conda/lib/python3.9/site-packages/matminer/datasets/dataset_retrieval.py:66[0m, in [0;36mload_dataset[0;34m(name, data_home, download_if_missing, pbar)[0m
[1;32m     64[0m dataset_metadata [38;5;241m=[39m _dataset_dict[name]
[1;32m     65[0m data_path [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(_get_data_home(data_home), name [38;5;241m+[39m [38;5;124m"[39m[38;5;124m.[39m[38;5;124m"[39m [38;5;241m+[39m dataset_metadata[[38;5;124m"[39m[38;5;124mfile_type[39m[38;5;124m"[39m])
[0;32m---> 66[0m [43m_validate_dataset[49m[43m([49m
[1;32m     67[0m [43m    [49m[43mdata_path[49m[43m,[49m
[1;32m     68[0m [43m    [49m[43mdataset_metadata[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43murl[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m
[1;32m     69[0m [43m    [49m[43mdataset_metadata[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mhash[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m
[1;32m     70[0m [43m    [49m[43mdownload_if_missing[49m[43m,[49m
[1;32m     71[0m [43m[49m[43m)[49m
[1;32m     73[0m df [38;5;241m=[39m load_dataframe_from_json(data_path, pbar[38;5;241m=[39mpbar)
[1;32m     75[0m [38;5;28;01mreturn[39;00m df

File [0;32m/opt/conda/lib/python3.9/site-packages/matminer/datasets/utils.py:89[0m, in [0;36m_validate_dataset[0;34m(data_path, url, file_hash, download_if_missing)[0m
[1;32m     87[0m [38;5;28;01mif[39;00m file_hash [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m     88[0m     [38;5;28;01mif[39;00m file_hash [38;5;241m!=[39m _get_file_sha256_hash(data_path):
[0;32m---> 89[0m         [38;5;28;01mraise[39;00m [38;5;167;01mUserWarning[39;00m(
[1;32m     90[0m             [38;5;124m"[39m[38;5;124mError, hash of downloaded file does not match that [39m[38;5;124m"[39m
[1;32m     91[0m             [38;5;124m"[39m[38;5;124mincluded in metadata, the data may be corrupt or altered[39m[38;5;124m"[39m
[1;32m     92[0m         )

[0;31mUserWarning[0m: Error, hash of downloaded file does not match that included in metadata, the data may be corrupt or altered
UserWarning: Error, hash of downloaded file does not match that included in metadata, the data may be corrupt or altered

